common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.home, name='com-home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('departments', views.dept, name='depts'),
    path('services', views.service, name='services'),
    path('department/<int:id>', views.department_details, name='department_details'),
    path('doctor/<int:id>', views.doctor_details, name='doctor_details'),
    path('doctor', views.doctor, name='dr'),
    path('user-type', views.user_type, name='user_type'),
    path('login', views.login, name='login'),
    path('register', views.patient_registration, name='pat_register'),
    path('make-appointment',views.make_appointment,name = 'make_appointment')
]

doctor/urls.py
from django.urls import path
from . import views

app_name = 'doctor'

urlpatterns = [
    path('home', views.doctor_home, name='dr_home'), 
    path('profile', views.profile, name='dr_profile'),
    path('profile/edit', views.edit_profile, name='edit_profile'),
    path('appointment', views.appointment, name='appointment'),
    path('search/patients',views.search_patients,name='search_patients'),
    path('change_password',views.change_password,name='change_pswd'),
    path('consulting',views.consulting,name='consulting'),
    path('patient/list',views.get_patients,name='get_patients'),
    path('prescription/<int:b_id>',views.add_prescription,name='add_prescription'),
    path('booking/<int:b_id>',views.patient_details,name='patient_details'),
    path('booking-submit',views.submit_prescription,name='submit_prescription'),

    

]

hospital_mgt/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('patient/', include('patient.urls')),
    path('doctor/', include('doctor.urls')),
    path('hms_admin/', include('hms_admin.urls')),
    path('staff/', include('staff.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('home', views.home, name='home'),
    path('appointment', views.appointment, name='appointment'),
    path('confirmation', views.confirmation, name='confirm'),
    path('my-bookings', views.my_bookings, name='bookings'),
    path('my-prescriptions', views.prescriptions, name='prescriptions'),
    path('change-password', views.change_password, name='chg-pwd'),
    path('my-profile', views.patient_profile, name='my-pro'),
    path('register', views.register, name='pt_reg'),
    path('edit_patient_profile', views.patient_edit, name='edit'),
    path('appointment-1', views.appt_1, name='appointment_1'),
    path('appointment-2', views.appt_2, name='appointment_2'),
    path('appointment-3', views.appt_3, name='appointment_3'),
    path('booking-confirmation/<int:bid>', views.appt_4, name='appointment_4'),
    # path('offline_booking',views.offline_booking,name = 'offline_booking'),
    path('my-bookings', views.my_bookings, name='my_bookings'),
    path('get-doctors', views.get_doctors, name='get_doctors'),
    path('check-availability', views.check_availability, name='check-availability'),
    path('booking/cancel/<int:id>',views.cancel_booking,name = 'cancel_booking'),
    path('logout',views.logout,name = 'logout'),
    path('booking/history',views.booking_history,name='booking_history'),
    path('view_Prescription',views.view_Prescription,name='view_Prescription')
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('home', views.staff_home, name='staff_home'),
    path('register',views.registration,name = 'register'),
    path('appointment/', views.appointments, name='appointment'),
    path('patient_search/', views.patient_search, name='patient-search'), 
    path('staff/', views.staff_list, name = 'staff-list'),
    path('profile/', views.profile, name="staff-prof"),
    path('logout/',views.log_out,name = 'logout')
]

doctor/models.py
from django.db import models
from hms_admin.models import Doctor
# Create your models here.
 

class Consultion(models.Model) : 

    doctor = models.ForeignKey(Doctor, on_delete = models.CASCADE)
    day = models.CharField(max_length = 20)
    time = models.CharField(max_length = 20)

 

doctor/views.py
import json
from django.shortcuts import render, redirect
from hms_admin.models import Doctor
from django.http import JsonResponse
from common.models import Patient
from patient.models import Booking
from datetime import datetime
from .serializers import *
from json import loads
# Create your views here.


def doctor_home(request):
    doctor = Doctor.objects.filter(
        id=request.session['doctor']).values('doctor_name')
    doc_name = doctor[0]['doctor_name']
    patients_count = Patient.objects.all().count()
   
   
    today = datetime.strftime(datetime.today(),"%d-%m-%Y")
    print(today)
   # today = "20-01-2023" 
     
    total_bookings = Booking.objects.filter(doctor = request.session['doctor'],booking_date = today, status = 'booked').count()
    print('jdwye',total_bookings)
    return render(request, 'doctor/doctor_home.html', {'doc_name': doc_name,'patients_count': patients_count, 'total_bookings' : total_bookings })


def profile(request):
    doctor = Doctor.objects.get(id=request.session['doctor'])
    return render(request, 'doctor/profile.html', {'doctor': doctor})


def edit_profile(request):
    doctor = Doctor.objects.get(id=request.session['doctor'])

    if request.method == 'POST':
        name = request.POST['dr_name']
        email = request.POST['dr_email']
        contact = request.POST['dr_contact']
        qualification = request.POST['dr_qual']
        experience = request.POST['dr_exp']
        fee = request.POST['dr_fee']

        doctor = Doctor.objects.get(id=request.session['doctor'])
        doctor.doctor_name = name
        doctor.doctor_email = email
        doctor.doctor_contact = contact
        doctor.qualification = qualification
        doctor.experience = experience
        doctor.fee = fee
        doctor.save()
        return redirect('doctor:dr_profile')

    return render(request, 'doctor/edit_profile.html', {'doctor': doctor})


def appointment(request):
     
    today = datetime.strftime(datetime.today(), "%d-%m-%Y")
    print(today)
    # today = "24-01-2023" 
    records = Booking.objects.filter(doctor = request.session['doctor'], status = 'booked',booking_date = today)

    return render(request, 'doctor/appointment.html',{'booking_records' : records})


def search_patients(request):
    patients_list = Patient.objects.all()
    return render(request, 'doctor/search_patients.html', {'patients_list': patients_list})




def change_password(request):

    error_msg = ''
    success_msg = ''

    if request.method == 'POST':

        old_password = request.POST['old_passwd']
        new_password = request.POST['new_passwd']
        confirm_password = request.POST['confirm_passwd']

        if new_password == confirm_password:
            if len(new_password) > 8:
                
                doctor = Doctor.objects.get(id=request.session['doctor'])
                
                if doctor.password == old_password:
                    doctor.password = new_password
                    doctor.save()
                    success_msg = 'Password Changed'
                
                else:
                    error_msg = 'Incorrect Password'

            else:
                error_msg = 'Password Should Be Min 8 Characters'

        else:
            error_msg = 'Password does\'nt match'

    return render(request, 'doctor/change_paswd.html', {'error_msg': error_msg, 'success_msg': success_msg})


def consulting(request):
    return render(request, 'doctor/consulting.html')


def get_patients(request):
    search_text = request.GET['search_text']
    
    search_result = Patient.objects.filter(patient_name__icontains = search_text)

    serialized_set = [{ 'id' : p.id, 'p_name' : p.patient_name.title() }  for p in search_result]
    return JsonResponse({'search_result' : serialized_set})


def patient_details(request,b_id):
    booking_record = Booking.objects.get(id = b_id) 
    
    return render(request,'doctor/patient_details.html', {'booking_record' : booking_record,})

def add_prescription(request,b_id):
    return render(request,'doctor/prescription.html', {'booking_id':b_id})

def submit_prescription(request):

    prescription = request.POST['prescription']
    # print("nvjhjxhvjvbh")

    prescription_obj=json.loads(prescription)

    print(prescription_obj[0]['booking'])
    bid=prescription_obj[0]['booking']
    booking=Booking.objects.get(id=bid)

    # params = loads(request.body)

     
    # print(params,'lkjhiu')
    serialized_data = PrescriptionSerializer(data = prescription_obj,many = True)

    if serialized_data.is_valid():
        serialized_data.save()
        booking.status="consulted"
        booking.save()


    
    else :
        print('errore')
        print(serialized_data.errors)
    return JsonResponse(serialized_data.data,safe=False)

 

doctor/templates/doctor/doctor_master.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="description" content="Orbitor,business,company,agency,modern,bootstrap4,tech,software" />
    <meta name="author" content="themefisher.com" />

    <title>Heavan Hospital Doctor Master Page</title>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico" />

    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" />
    <!-- Icon Font Css -->
    <link rel="stylesheet" href="{% static 'plugins/icofont/icofont.min.css' %}" />
    <!-- Slick Slider  CSS -->
    <link rel="stylesheet" href=" {% static 'plugins/slick-carousel/slick/slick.css' %}" />
    <link rel="stylesheet" href=" {% static 'plugins/slick-carousel/slick/slick-theme.css' %}" />

    <!-- Main Stylesheet -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" />

    <!-- Logout  -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



    {% block header %}
    <!-- Add style tag for individual pages  -->
    {% endblock %}

</head>

<body id="top">
    <header>
        <div class="header-top-bar">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6">
                        <ul class="top-bar-info list-inline-item pl-0 mb-0">
                            <li class="list-inline-item">
                                <a href="mailto:support@gmail.com"><i
                                        class="icofont-support-faq mr-2"></i>support@novena.com</a>
                            </li>
                            <li class="list-inline-item">
                                <i class="icofont-location-pin mr-2"></i>Address Ta-134/A, New
                                York, USA
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <div class="text-lg-right top-right-bar mt-2 mt-lg-0">
                            <a href="tel:+23-345-67890">
                                <span>Call Now : </span>
                                <span class="h4">823-4565-13456</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navigation" id="navbar">
            <div class="container">
                <a class="navbar-brand" href="{% url 'common:com-home' %}">
					<img src="{% static 'images/heavan.png' %}" alt="" class="img-fluid">
				</a>
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain"
                    aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icofont-navigation-menu"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarmain">
                    <ul class="navbar-nav ml-auto" style="align-items: right">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'doctor:dr_home' %}">Home</a>
                        </li>

                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="dropdown03" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false"> Profile </a>
                            <ul class="dropdown-menu" aria-labelledby="dropdown03">
                                <li><a class="dropdown-item" href="{% url 'doctor:dr_profile' %}"> My Profile </a></li>
                                <li><a class="dropdown-item" href="{% url 'doctor:change_pswd' %}"> Change Password </a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'doctor:search_patients' %}"> Patients </a>
                        </li>

                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'doctor:appointment' %}"> Appointments</a>
                        </li>

                       

                         <!-- Avatar -->
                         <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#"
                                id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown"
                                aria-expanded="false">
                                <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img (31).webp"
                                    class="rounded-circle" height="50" alt="Avatar" />
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li>
                                    <a class="dropdown-item" href="{% url 'doctor:dr_profile' %}">My profile</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'doctor:change_pswd' %}">Change Password</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'common:com-home' %}">Logout</a>
                                </li>
                            </ul>
                        </li>


                        <!-- Logout  -->
                        <!-- <li class="nav-item active">
                            <a class="nav-link" href="{% url 'common:com-home' %}">
                                <span class="material-symbols-rounded"> Logout </span>
                            </a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <br />

    {% block content %}


    {% endblock %}


    <!-- footer Start -->
    <footer class="footer section gray-bg">
        <div class="container">
            <div class="row">
                <!-- <div class="col-lg-4 mr-auto col-sm-6">
                    <div class="widget mb-5 mb-lg-0">
                        <div class="logo mb-4">
                            <img src="{% static 'images/logo.png' %}" alt="" class="img-fluid" />
                        </div>
                        <p>
                            Tempora dolorem voluptatum nam vero assumenda voluptate, facilis
                            ad eos obcaecati tenetur veritatis eveniet distinctio possimus.
                        </p>

                        <ul class="list-inline footer-socials mt-4">
                            <li class="list-inline-item">
                                <a href="https://www.facebook.com/themefisher"><i class="icofont-facebook"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://twitter.com/themefisher"><i class="icofont-twitter"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.pinterest.com/themefisher/"><i class="icofont-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div> -->

                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="widget mb-5 mb-lg-0">
                        <h4 class="text-capitalize mb-3">Department</h4>
                        <div class="divider mb-4"></div>

                        <ul class="list-unstyled footer-menu lh-35">
                            <li><a href="#">Surgery </a></li>
                            <li><a href="#">Wome's Health</a></li>
                            <li><a href="#">Radiology</a></li>
                            <li><a href="#">Cardioc</a></li>
                            <li><a href="#">Medicine</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="widget mb-5 mb-lg-0">
                        <h4 class="text-capitalize mb-3">Support</h4>
                        <div class="divider mb-4"></div>

                        <ul class="list-unstyled footer-menu lh-35">
                            <li><a href="#">Terms & Conditions</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Company Support </a></li>
                            <li><a href="#">FAQuestions</a></li>
                            <li><a href="#">Company Licence</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="widget widget-contact mb-5 mb-lg-0">
                        <h4 class="text-capitalize mb-3">Get in Touch</h4>
                        <div class="divider mb-4"></div>

                        <div class="footer-contact-block mb-4">
                            <div class="icon d-flex align-items-center">
                                <i class="icofont-email mr-3"></i>
                                <span class="h6 mb-0">Support Available for 24/7</span>
                            </div>
                            <h4 class="mt-2">
                                <a href="tel:+23-345-67890">Support@email.com</a>
                            </h4>
                        </div>

                        <div class="footer-contact-block">
                            <div class="icon d-flex align-items-center">
                                <i class="icofont-support mr-3"></i>
                                <span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
                            </div>
                            <h4 class="mt-2">
                                <a href="tel:+23-345-67890">+23-456-6588</a>
                            </h4>
                        </div>

                        <ul class="list-inline footer-socials mt-4">
                            <li class="list-inline-item">
                                <a href="https://www.facebook.com/themefisher"><i class="icofont-facebook"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://twitter.com/themefisher"><i class="icofont-twitter"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.pinterest.com/themefisher/"><i class="icofont-linkedin"></i></a>
                            </li>
                        </ul>

                    </div>
                </div>
            </div>

            <div class="footer-btm py-4 mt-5">
                <div class="row align-items-center justify-content-between">
                    <div class="col-lg-6">
                        <div class="copyright">
                            &copy; Copyright Reserved to
                            <span class="text-color">Novena</span> by
                            <a href="https://themefisher.com/" target="_blank">Themefisher</a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="subscribe-form text-lg-right mt-5 mt-lg-0">
                            <form action="#" class="subscribe">
                                <input type="text" class="form-control" placeholder="Your Email address" />
                                <a href="#" class="btn btn-main-2 btn-round-full">Subscribe</a>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <a class="backtop js-scroll-trigger" href="#top">
                            <i class="icofont-long-arrow-up"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- 
    Essential Scripts
    =====================================-->

    <!-- Main jQuery -->
    <script src="{% static 'plugins/jquery/jquery.js' %} plugins/jquery/jquery.js"></script>
    <!-- Bootstrap 4.3.2 -->
    <script src="{% static 'plugins/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/counterup/jquery.easing.js' %}"></script>
    <!-- Slick Slider -->
    <script src="{% static 'plugins/slick-carousel/slick/slick.min.js' %}"></script>
    <!-- Counterup -->
    <script src=" {% static 'plugins/counterup/jquery.waypoints.min.js' %}"></script>

    <script src=" {% static 'plugins/shuffle/shuffle.min.js' %}"></script>
    <script src=" {% static 'plugins/counterup/jquery.counterup.min.js' %}"></script>
    <!-- Google Map -->
    <script src=" {% static 'plugins/google-map/map.js' %}"></script>
    <script
        src=" https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>

    <script src=" {% static 'js/script.js' %}"></script>
    <script src=" {% static 'js/contact.js' %}"></script>
</body>

</html>

doctor/templates/doctor/profile.html
{% extends 'doctor/doctor_master.html' %}

{% load static %}

{% block header %}
<link rel="stylesheet" href=" {% static 'css/dr_profile.css' %}">
{% endblock %}

{% block content %}

<section class="prof_section">

    <div class="container" >

        <div class="main-body">

            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ doctor.pic.url }}" alt="Admin" class="rounded-circle"
                                    width="150">
                                <div class="mt-3">
                                    {{ doctor.doctor_name }}
                                    <h4>  </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mt-4">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect>
                                        <line x1="16" y1="2" x2="16" y2="6"></line>
                                        <line x1="8" y1="2" x2="8" y2="6"></line>
                                        <line x1="3" y1="10" x2="21" y2="10"></line>
                                    </svg> &ensp;
                                    <a href="{% url 'doctor:appointment' %}"> Appointments</a> 
                                    <!-- <a href="{% url 'doctor:consulting' %}"> Consulting</a>  -->

                                </h5>

                            </li>
                          
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                                        <circle cx="8.5" cy="7" r="4"></circle>
                                        <line x1="20" y1="8" x2="20" y2="14"></line>
                                        <line x1="23" y1="11" x2="17" y2="11"></line>
                                    </svg> &ensp;
                                    <a href="{% url 'doctor:search_patients' %}"> Patients </a> 
                                </h5>

                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="mt-1 mb-1">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" class="feather feather-activity">
                                        <rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect>
                                        <path d="M7 11V7a5 5 0 0 1 9.9-1"></path>
                                    </svg> &ensp;
                                  <a href="{% url 'doctor:change_pswd' %}">Change Password</a>  
                                </h5>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="col-md-8"> 
                    <div class="card mb-3">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Name</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    
                                       {{ doctor.doctor_name }}
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Email ID</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.doctor_email }}
                                </div>                                
                            </div>
                            <hr>
                            
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Contact Number</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.doctor_contact }}
                                    
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Department</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.department.department }}
                                    
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Qualification</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.qualification }}
                                    
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Experience</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.experience }}
                                     
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-4">
                                    <h6 class="mb-0">Consultancy Fees</h6>
                                </div>
                                <div class="col-sm-8 text-secondary">
                                    {{ doctor.fee }}
                                     
                                </div>
                            </div>

                            <hr>
                            <div class="row">
                                <div class="col-sm-12">
                                    <a class="btn btn-primary "  
                                        href="{% url 'doctor:edit_profile' %}">Edit</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>


{% endblock %}