common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.home, name='com-home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('departments', views.dept, name='depts'),
    path('services', views.service, name='services'),
    path('department/<int:id>', views.department_details, name='department_details'),
    path('doctor/<int:id>', views.doctor_details, name='doctor_details'),
    path('doctor', views.doctor, name='dr'),
    path('user-type', views.user_type, name='user_type'),
    path('login', views.login, name='login'),
    path('register', views.patient_registration, name='pat_register'),
    path('make-appointment',views.make_appointment,name = 'make_appointment')
]

hospital_mgt/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('patient/', include('patient.urls')),
    path('doctor/', include('doctor.urls')),
    path('hms_admin/', include('hms_admin.urls')),
    path('staff/', include('staff.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('home', views.home, name='home'),
    path('appointment', views.appointment, name='appointment'),
    path('confirmation', views.confirmation, name='confirm'),
    path('my-bookings', views.my_bookings, name='bookings'),
    path('my-prescriptions', views.prescriptions, name='prescriptions'),
    path('change-password', views.change_password, name='chg-pwd'),
    path('my-profile', views.patient_profile, name='my-pro'),
    path('register', views.register, name='pt_reg'),
    path('edit_patient_profile', views.patient_edit, name='edit'),
    path('appointment-1', views.appt_1, name='appointment_1'),
    path('appointment-2', views.appt_2, name='appointment_2'),
    path('appointment-3', views.appt_3, name='appointment_3'),
    path('booking-confirmation/<int:bid>', views.appt_4, name='appointment_4'),
    # path('offline_booking',views.offline_booking,name = 'offline_booking'),
    path('my-bookings', views.my_bookings, name='my_bookings'),
    path('get-doctors', views.get_doctors, name='get_doctors'),
    path('check-availability', views.check_availability, name='check-availability'),
    path('booking/cancel/<int:id>',views.cancel_booking,name = 'cancel_booking'),
    path('logout',views.logout,name = 'logout'),
    path('booking/history',views.booking_history,name='booking_history'),
    path('view_Prescription',views.view_Prescription,name='view_Prescription')
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('home', views.staff_home, name='staff_home'),
    path('register',views.registration,name = 'register'),
    path('appointment/', views.appointments, name='appointment'),
    path('patient_search/', views.patient_search, name='patient-search'), 
    path('staff/', views.staff_list, name = 'staff-list'),
    path('profile/', views.profile, name="staff-prof"),
    path('logout/',views.log_out,name = 'logout')
]

common/models.py
from django.db import models

# Create your models here.

class Patient(models.Model):
    patient_name = models.CharField(max_length = 50)
    email = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    age = models.IntegerField()
    phone = models.BigIntegerField()
    blood_grp = models.CharField(max_length=10)
    dob = models.CharField(max_length=20)
    gender = models.CharField(max_length=10)
    status = models.CharField(max_length=20, default = 'active')
    pic = models.ImageField(upload_to = 'patient/', default = 'static/default-user.png')

    class Meta :
        db_table = 'patient_tb'

common/views.py
import string
from django.shortcuts import render,redirect,reverse
from hms_admin.models import Staff,Doctor
from .models import Patient
from hms_admin.models import Department
# Create your views here.
def home(request):
    return render(request,'common/homepage.html')

def user_type(request):
    return render(request,'common/user_type.html')    
 
def about(request):
    return render(request,'common/about.html')

def contact(request):
    return render(request,'common/contact.html')

def dept(request):
    departments = Department.objects.all()
    return render(request,'common/department.html',{'departments':departments,})

def service(request):
    return render(request,'common/service.html')


def patient_registration(request):

    error_msg = ''
    success_msg = ''
    if request.method == 'POST':

        name = request.POST['pat_name']
        address = request.POST['pat_address']
        age = request.POST['pat_age']
        blood_group = request.POST['blood_grp']
        contact = request.POST['pat_phno']
        dob = request.POST['pat_dob']
        gender = request.POST['gender']
        email = request.POST['pat_email']

        record_exist = Patient.objects.filter(email = email).exists()

        if not record_exist :
            if 'pic' in request.FILES : # here pic is the name attribute of fileuploader
                pic = request.FILES['pic']
        
                patient_record = Patient( patient_name = name ,email = email, address = address , age = age , blood_grp = blood_group , 
                phone = contact , dob = dob , gender = gender , pic = pic )
                
            else :

                patient_record = Patient( patient_name = name ,email = email, address = address , age = age , blood_grp = blood_group , 
                phone = contact , dob = dob , gender = gender )

            
            patient_record.save()
            success_msg = 'Record Added Succesfully'

        else:
            error_msg = 'Email Exists'
    return render(request,'common/patient_register.html', {'success_msg' : success_msg, 'error_msg' : error_msg})

def login(request):
    user_type = request.GET['user']
    msg = ''
    
    # if 'patient' in request.session :
    #     return redirect('patient:home')

    # if 'doctor' in request.session :
    #     return redirect('doctor:dr_home')

    # if 'staff' in request.session :
    #     return redirect('staff:staff_home') 

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        if user_type ==  'staff':
             
            try :
                staff = Staff.objects.get(mail = username, password = password)
                request.session['staff'] = staff.id
                return redirect('staff:staff_home')
            except :
                msg = 'Invalid Username Or Password'

        if user_type == 'doc':
             
            try :
                doctor = Doctor.objects.get(username = username, password = password)
                request.session['doctor'] = doctor.id
                return redirect('doctor:dr_home')
            except :
                msg = 'Invalid Username Or Password'
        
        if user_type == 'patient':
             
            try :
                patient = Patient.objects.get(email = username, phone = password)
                request.session['patient'] = patient.id
                return redirect('patient:home')
            #     if request.session['log'] == True :
            #         return redirect('patient:appointment_1')

            #     request.session['log'] = False
            #     return redirect('patient:home')
            # except Exception as e :
            #     print(e)
            except:
                msg = 'Invalid Username Or Password'

        
    return render(request,'common/login.html', {'error_msg' : msg})

def department_details(request,id):
    department = Department.objects.get(id = id)
    doctors = Doctor.objects.filter(department = id)
    return render(request,'common/department_details.html',{ 'department': department,'doctors' : doctors})

def doctor_details(request,id):
    doctor = Doctor.objects.get(id = id)
    return render(request,'common/doctor_details.html',{'doctor': doctor,})

def doctor(request):
    return render(request,'common/hms_doctor.html')


def make_appointment(request):
 
    if 'patient' in request.session:
        return redirect('patient:appointment_1') 

  
    request.session['log'] = True
    return redirect(reverse('common:login') + '?user=patient') 
    

common/templates/common/about.html
{% extends 'common/index.html' %}
{% load static %}

{% block header %}
{% endblock %}


{% block content %}

<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">About Us</span>
          <h1 class="text-capitalize mb-5 text-lg">About Us</h1>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section about-page">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<h2 class="title-color">Personal care for your healthy living</h2>
			</div>
			<div class="col-lg-8">
				<p>
					Personalized Medical Assistant for all your healthcare needs.<br />
					Book instant appointment, pay securely, eConsult with our doctors and save all your health records at one place are some of the benefits of OneHeavan App.
					It is everything you need, to manage your family Health
				</p>
				<img src="{% static 'images/about/sign.png' %}" alt="" class="img-fluid">
			</div>
		</div>
	</div>
</section>

{% endblock %}

common/templates/common/department.html
{% extends 'common/index.html' %}
{% load static %}

{% block header %}

{% endblock %}


{% block content %}

<section class="page-title bg-1">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block text-center">
					<h1 class="text-capitalize mb-5 text-lg">Departments</h1>
				</div>
			</div>
		</div>
	</div>
</section>


<section class="section service-2">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-7 text-center">
			</div>
		</div>

		<div class="row">
			{% for department in departments %}
			<div class="col-lg-4 col-md-6 ">
				<div class="department-block mb-5">
					<a href="{% url 'common:department_details' department.id %}"> <img src="{{ department.pic.url }}"
							alt="" width="350px" height="250px"> </a>
					<div class="content">
 
							<h4 class="mt-4 mb-2 title-color">{{ department.department | title }}</h4>
				 
						<p class="mb-4">{{ department.description }}</p>
						 
					</div>
				</div>
			</div>

			{% endfor %}
		</div>









	</div>
</section>



{% endblock %}

common/templates/common/department_details.html
{% extends 'common/index.html' %}
{% load static %}

{% block header %}

<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.css"
  rel="stylesheet"
/>

<script src=" {% static 'js/doctor_cards.js' %}"></script>


<link rel="stylesheet" href="{% static 'css/doctor_cards.css' %}" />

<style>

</style>

<script>

</script>

{% endblock %}

{% block content %}

<section class="page-title bg-1">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block text-center">
					<h1 class="text-capitalize mb-5 text-lg">{{ department.department }}</h1>
				</div>
			</div>
		</div>
	</div>
</section>


<section class="section department-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				
			</div>
		</div>

		<div class="row">
			<div class="col-lg-10">
				<div class="department-content mt-5">
					<h3 class="text-md">Medecine and Health</h3>
					<div class="divider my-4"></div>
					<p class="lead">{{ department.description }}</p>
				</div>
			</div>
		</div>
	</div>

</section>


<section class="section team">
	<div class="container">
		<div class="row">
			<div class="col-lg-6">
				<div class="section-title text-center">
					<h3 class="text-md" style="align-content: left;">Our Doctors</h3>
					<div class="divider mx-auto my-4"></div>
				</div>
			</div>
		</div>

		<div class="row">

			{% for doctor in doctors %}
			<div class="col-lg-3 col-md-6 col-sm-6">
				<a href="{% url 'common:doctor_details' doctor.id %}" style="text-decoration: none;">
				<div class="team-block mb-5 mb-lg-0">
					<img src="{{ doctor.pic.url }}" alt="" class="img-fluid w-100">

					<div class="content">
						<h4 class="mt-4 mb-0"> {{ doctor.doctor_name | title }} </h4>
						<p> {{ doctor.qualification }} </p>
					</div>
				</div>
			</a>
			</div>

			{% endfor %}

		</div>
	</div>
</section>




{% endblock %}

common/templates/common/doctor_details.html
{% extends 'common/index.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}

<section class="page-title bg-1">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <!-- <span class="text-white">Doctor Details</span> -->
          <h1 class="text-capitalize mb-5 text-lg">{{ doctor.doctor_name | title }}</h1>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section doctor-single">
	<div class="container">
		<div class="row">
			<div class="col-lg-4 col-md-6">
				<div class="doctor-img-block">
					<img src="{{ doctor.pic.url }}" alt="" class="img-fluid w-100">

					<div class="info-block mt-4">
						<h4 class="mb-0">{{ doctor.doctor_name | title }}</h4>
						<p>{{ doctor.qualification |  upper }}</p>

						 
					</div>
				</div>
			</div>

			<div class="col-lg-8 col-md-6">
				<div class="doctor-details mt-4 mt-lg-0">
					<h2 class="text-md">About Me</h2>
					<div class="divider my-4"></div>
					 <p>Name : {{ doctor.doctor_name | title }}</p>
					 <p>Email : {{ doctor.doctor_email }} </p>
					 <p>Qualification : {{ doctor.qualification }} </p>
					 <p>Contact : {{ doctor.doctor_contact }} </p>
					 <p>Fee : Rs {{ doctor.fee }}</p>
					 <br>

					<a href="{% url 'common:make_appointment' %}" class="btn btn-main-2 btn-round-full mt-3">Make an Appoinment<i class="icofont-simple-right ml-2  "></i></a>
				</div>
			</div>
		</div>
	</div>
</section>


{% endblock %}

common/templates/common/index.html
{% load static %}
<!-- All other pages extends this page -->

<!DOCTYPE html>
<html lang="zxx">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="description" content="Orbitor,business,company,agency,modern,bootstrap4,tech,software">
	<meta name="author" content="themefisher.com">

	<title>Heavan Care Hospital Master Page</title>

	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico" />

	<!-- bootstrap.min css -->
	<link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
	<!-- Icon Font Css -->
	<link rel="stylesheet" href="{% static 'plugins/icofont/icofont.min.css' %}">
	<!-- Slick Slider  CSS -->
	<link rel="stylesheet" href=" {% static 'plugins/slick-carousel/slick/slick.css' %}">
	<link rel="stylesheet" href=" {% static 'plugins/slick-carousel/slick/slick-theme.css' %}">

	<!-- Main Stylesheet -->
	<link rel="stylesheet" href=" {% static 'css/style.css' %}">

	<!-- custom style  -->
	<!-- <link rel="stylesheet" href="static/css/pt_register.css"> -->

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

	<script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>


	{% block header %}
	<!-- Add style tag for individual pages  -->
	{% endblock %}

</head>

<body id="top">

	<header>
		<div class="header-top-bar">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-lg-6">
						<ul class="top-bar-info list-inline-item pl-0 mb-0">
							<li class="list-inline-item"><a href="mailto:support@gmail.com"><i
										class="icofont-support-faq mr-2"></i>support@heavancare.com</a></li>
							<li class="list-inline-item"><i class="icofont-location-pin mr-2"></i>Address Ta-134/A,
								Calicut,India </li>
						</ul>
					</div>
					<div class="col-lg-6">
						<div class="text-lg-right top-right-bar mt-2 mt-lg-0">
							<a href="tel:+23-345-67890">
								<span>Call Now : </span>
								<span class="h4">823-4565-13456</span>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>	

		<nav class="navbar navbar-expand-lg navigation" id="navbar">
			<div class="container">
				<a class="navbar-brand" href="{% url 'common:com-home' %}">
					<img src="{% static 'images/heavan.png' %}" alt="" class="img-fluid">
				</a>
		
				<button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain"
					aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
					<span class="icofont-navigation-menu"></span>
				</button>
		
				<div class="collapse navbar-collapse" id="navbarmain">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'common:com-home' %}">Home</a>
						</li>
						<li class="nav-item"><a class="nav-link" href="{% url 'common:about' %}">About</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'common:services' %}">Services</a></li>
		
						<li class="nav-item active">
							<a class="nav-link" href="{% url 'common:depts' %}">
                                Departments
                            </a>
						</li>					
		
						<li class="nav-item"><a class="nav-link" href="{% url 'common:contact' %}">Contact</a></li>
							
						<li class="nav-item"><a class="nav-link" href="{% url 'common:user_type' %}">Login</a></li>	
		
					</ul>
				</div>
			</div>
		</nav>
		</header>
		
		
	{% block content %}

	

	{% endblock %}


	<!-- footer Start -->
	<footer class="footer section gray-bg">
		<div class="container">
			<div class="row">

				<!-- <div class="col-lg-4 mr-auto col-sm-6">
					<div class="widget mb-5 mb-lg-0">
						<div class="logo mb-4">
							<img src="{% static 'images/logo.png' %}" alt="" class="img-fluid">
						</div>
						<p>Tempora dolorem voluptatum nam vero assumenda voluptate, facilis ad eos obcaecati tenetur
							veritatis eveniet distinctio possimus.</p>

						<ul class="list-inline footer-socials mt-4">
							<li class="list-inline-item"><a href="https://www.facebook.com/themefisher"><i
										class="icofont-facebook"></i></a></li>
							<li class="list-inline-item"><a href="https://twitter.com/themefisher"><i
										class="icofont-twitter"></i></a></li>
							<li class="list-inline-item"><a href="https://www.pinterest.com/themefisher/"><i
										class="icofont-linkedin"></i></a></li>
						</ul>
					</div>
				</div> -->

				<div class="col-lg-4 col-md-6 col-sm-6">
					<div class="widget mb-5 mb-lg-0">
						<h4 class="text-capitalize mb-3">Department</h4>
						<div class="divider mb-4"></div>

						<ul class="list-unstyled footer-menu lh-35">
							<li><a href="#">Surgery </a></li>
							<li><a href="#">Women's Health</a></li>
							<li><a href="#">Radiology</a></li>
							<li><a href="#">Cardiac</a></li>
							<li><a href="#">Medicine</a></li>
						</ul>
					</div>
				</div>

				<div class="col-lg-4 col-md-6 col-sm-6">
					<div class="widget mb-5 mb-lg-0">
						<h4 class="text-capitalize mb-3">Support</h4>
						<div class="divider mb-4"></div>

						<ul class="list-unstyled footer-menu lh-35">
							<li><a href="#">Terms & Conditions</a></li>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Company Support </a></li>
							<li><a href="#">FAQuestions</a></li>
							<li><a href="#">Company Licence</a></li>
						</ul>
					</div>
				</div>

				<div class="col-lg-4 col-md-6 col-sm-6">
					<div class="widget widget-contact mb-5 mb-lg-0">
						<h4 class="text-capitalize mb-3">Get in Touch</h4>
						<div class="divider mb-4"></div>

						<div class="footer-contact-block mb-4">
							<div class="icon d-flex align-items-center">
								<i class="icofont-email mr-3"></i>
								<span class="h6 mb-0">Support Available for 24/7</span>
							</div>
							<h4 class="mt-2"><a href="tel:+23-345-67890">Support@email.com</a></h4>
						</div>

						<div class="footer-contact-block">
							<div class="icon d-flex align-items-center">
								<i class="icofont-support mr-3"></i>
								<span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
							</div>
							<h4 class="mt-2"><a href="tel:+23-345-67890">+23-456-6588</a></h4>
						</div>
						<ul class="list-inline footer-socials mt-4">
							<li class="list-inline-item"><a href="https://www.facebook.com/themefisher"><i
										class="icofont-facebook"></i></a></li>
							<li class="list-inline-item"><a href="https://twitter.com/themefisher"><i
										class="icofont-twitter"></i></a></li>
							<li class="list-inline-item"><a href="https://www.pinterest.com/themefisher/"><i
										class="icofont-linkedin"></i></a></li>
						</ul>
					</div>
				</div>
			</div>

			<div class="footer-btm py-4 mt-5">
				<div class="row align-items-center justify-content-between">
					<div class="col-lg-6">
						<div class="copyright">
							&copy; Copyright Reserved to <span class="text-color">Novena</span> by <a
								href="https://themefisher.com/" target="_blank">Themefisher</a>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="subscribe-form text-lg-right mt-5 mt-lg-0">
							<form action="#" class="subscribe">
								<input type="text" class="form-control" placeholder="Your Email address">
								<a href="#" class="btn btn-main-2 btn-round-full">Subscribe</a>
							</form>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-4">
						<a class="backtop js-scroll-trigger" href="#top">
							<i class="icofont-long-arrow-up"></i>
						</a>
					</div>
				</div>
			</div>
		</div>
	</footer>



	<!-- 
    Essential Scripts
    =====================================-->


	<!-- Main jQuery -->
	<!-- <script src="{% static 'plugins/jquery/jquery.js' %} plugins/jquery/jquery.js"></script> -->
	<!-- Bootstrap 4.3.2 -->
	<script src="{% static 'plugins/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'plugins/counterup/jquery.easing.js' %}"></script>
	<!-- Slick Slider -->
	<script src="{% static 'plugins/slick-carousel/slick/slick.min.js' %}"></script>
	<!-- Counterup -->
	<script src=" {% static 'plugins/counterup/jquery.waypoints.min.js' %}"></script>

	<script src=" {% static 'plugins/shuffle/shuffle.min.js' %}"></script>
	<script src=" {% static 'plugins/counterup/jquery.counterup.min.js' %}"></script>
	<!-- Google Map -->
	<script src=" {% static 'plugins/google-map/map.js' %}"></script>
	<script
		src=" https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>

	<script src=" {% static 'js/script.js' %}"></script>
	<script src=" {% static 'js/contact.js' %}"></script>

</body>

</html>

common/templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link rel="stylesheet" href=" {% static 'css/login.css' %}" />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />

    <link rel="stylesheet" href="CSS/jquery.mobile-1.0a4.1.min.css" />
    <script src="JS/jquery-1.5.2.min.js" type="text/javascript" ></script>
    <script src="JS/jquery.mobile-1.0a4.1.min.js" type="text/javascript" ></script>

  </head>

  <body>
    <section class="login">
      <div class="login_box">
        <div class="left">
          <div class="top_link">
            <a href="{% url 'common:com-home' %}">
              <img
                src="https://drive.google.com/u/0/uc?id=16U__U5dJdaTfNGobB_OpwAJ73vM50rPV&export=download"
                alt=""
              />
              Return home</a
            >
          </div>
 
          <div class="contact">
            
            <form method="POST">
            
              {% csrf_token %}
              <h3>LOGIN</h3>

              <input type="text" name="username" placeholder="USERNAME" />
              <input type="password"  name = "password" placeholder="PASSWORD" />
           
              <button class="submit">LOGIN</button>
              <p style="color: red;">   {{ error_msg }}</p>
              <span>
                New User ? <a href="{% url 'common:pat_register' %}"> Register </a>
              </span>
            </form>
           
          </div>
        </div>

        <div class="right">
          <div class="right-text">
            <h2>HOSPITAL</h2>
            <h2>MANAGEMENT SYSTEM</h2>
          </div>
          <div class="right-inductor">
            <img
              src="https://lh3.googleusercontent.com/fife/ABSRlIoGiXn2r0SBm7bjFHea6iCUOyY0N2SrvhNUT-orJfyGNRSMO2vfqar3R-xs5Z4xbeqYwrEMq2FXKGXm-l_H6QAlwCBk9uceKBfG-FjacfftM0WM_aoUC_oxRSXXYspQE3tCMHGvMBlb2K1NAdU6qWv3VAQAPdCo8VwTgdnyWv08CmeZ8hX_6Ty8FzetXYKnfXb0CTEFQOVF4p3R58LksVUd73FU6564OsrJt918LPEwqIPAPQ4dMgiH73sgLXnDndUDCdLSDHMSirr4uUaqbiWQq-X1SNdkh-3jzjhW4keeNt1TgQHSrzW3maYO3ryueQzYoMEhts8MP8HH5gs2NkCar9cr_guunglU7Zqaede4cLFhsCZWBLVHY4cKHgk8SzfH_0Rn3St2AQen9MaiT38L5QXsaq6zFMuGiT8M2Md50eS0JdRTdlWLJApbgAUqI3zltUXce-MaCrDtp_UiI6x3IR4fEZiCo0XDyoAesFjXZg9cIuSsLTiKkSAGzzledJU3crgSHjAIycQN2PH2_dBIa3ibAJLphqq6zLh0qiQn_dHh83ru2y7MgxRU85ithgjdIk3PgplREbW9_PLv5j9juYc1WXFNW9ML80UlTaC9D2rP3i80zESJJY56faKsA5GVCIFiUtc3EewSM_C0bkJSMiobIWiXFz7pMcadgZlweUdjBcjvaepHBe8wou0ZtDM9TKom0hs_nx_AKy0dnXGNWI1qftTjAg=w1920-h979-ft"
              alt=""
            />
          </div>
        </div>
      </div>
    </section>
   
  </body>
</html>