hospital_mgt/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('patient/', include('patient.urls')),
    path('doctor/', include('doctor.urls')),
    path('hms_admin/', include('hms_admin.urls')),
    path('staff/', include('staff.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('home', views.home, name='home'),
    path('appointment', views.appointment, name='appointment'),
    path('confirmation', views.confirmation, name='confirm'),
    path('my-bookings', views.my_bookings, name='bookings'),
    path('my-prescriptions', views.prescriptions, name='prescriptions'),
    path('change-password', views.change_password, name='chg-pwd'),
    path('my-profile', views.patient_profile, name='my-pro'),
    path('register', views.register, name='pt_reg'),
    path('edit_patient_profile', views.patient_edit, name='edit'),
    path('appointment-1', views.appt_1, name='appointment_1'),
    path('appointment-2', views.appt_2, name='appointment_2'),
    path('appointment-3', views.appt_3, name='appointment_3'),
    path('booking-confirmation/<int:bid>', views.appt_4, name='appointment_4'),
    # path('offline_booking',views.offline_booking,name = 'offline_booking'),
    path('my-bookings', views.my_bookings, name='my_bookings'),
    path('get-doctors', views.get_doctors, name='get_doctors'),
    path('check-availability', views.check_availability, name='check-availability'),
    path('booking/cancel/<int:id>',views.cancel_booking,name = 'cancel_booking'),
    path('logout',views.logout,name = 'logout'),
    path('booking/history',views.booking_history,name='booking_history'),
    path('view_Prescription',views.view_Prescription,name='view_Prescription')
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('home', views.staff_home, name='staff_home'),
    path('register',views.registration,name = 'register'),
    path('appointment/', views.appointments, name='appointment'),
    path('patient_search/', views.patient_search, name='patient-search'), 
    path('staff/', views.staff_list, name = 'staff-list'),
    path('profile/', views.profile, name="staff-prof"),
    path('logout/',views.log_out,name = 'logout')
]

patient/models.py
from django.db import models
from common.models import Patient
from hms_admin.models import Doctor


class Booking(models.Model) :
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE,null=True )
    patient_name = models.CharField(max_length = 30)
    gender = models.CharField(max_length = 10)
    mobile = models.BigIntegerField()
    age = models.IntegerField()
    reference_no = models.CharField(max_length = 30)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    time = models.CharField(max_length = 10)
    booking_date = models.CharField(max_length = 20)
    status = models.CharField(max_length = 20, default = 'booked')

    class Meta : 
        db_table = 'booking_tb'


class Presciption(models.Model):
    booking = models.ForeignKey(Booking,on_delete = models.CASCADE)
    medicine_name = models.CharField(max_length = 20)
    days = models.IntegerField()
    medicine_time = models.CharField(max_length = 20)
    intake_time = models.CharField(max_length = 20)

    class Meta : 
        db_table = 'prescription_tb'

patient/views.py
from django.shortcuts import render,redirect
from common.models import Patient
from doctor.serializers import PrescriptionSerializer
from . models import Booking, Presciption
from hms_admin.models import Department,Doctor,Consultation
from datetime import datetime
from random import randint
from django.db.models import Q
from .services import get_slots,create_slots,create_bookings,generate_slot
from django.http import JsonResponse,HttpResponse
# Create your views here.
def home(request):
    patient = Patient.objects.filter(id = request.session['patient']).values('patient_name')
    pat_name = patient[0]['patient_name']
    booking_count = Booking.objects.filter(patient = request.session['patient']).count()
    cancelled_count = Booking.objects.filter(patient = request.session['patient'], status = 'cancelled').count()
    
    last_booking = Booking.objects.filter(patient = request.session['patient']).values('booking_date','time','reference_no','status')
    
    context = {
        'pat_name' : pat_name,
        'last_booking' : last_booking,
        'booking' :  booking_count,
        'cancelled_count':cancelled_count
        }
    return render(request,'patient/patient_home.html', context)

def appointment(request): # old appointment
    return render(request,'patient/appointment.html')

def confirmation(request): # old confirmation
    return render(request,'patient/confirmation.html')

def my_bookings(request):
    return render(request,'patient/my_bookings.html')

def prescriptions(request):
    return render(request,'patient/prescriptions.html')

def change_password(request):

    error_msg = ''
    success_msg = ''

    if request.method == 'POST':

        old_password = request.POST['old_pswd']
        new_password = request.POST['new_pswd']
        confirm_password = request.POST['confirm_pswd']
        patient = Patient.objects.get(id = request.session['patient']) # getting patient details
        print(old_password)
        if patient.password == old_password :

            if new_password == confirm_password :

                if len(new_password) > 8 :
                    patient.password = new_password
                    patient.save()
                    success_msg = 'your password has changed'
                else :
                    error_msg = 'your password shold be minimum 8 characters'
            else :
                error_msg = 'password doesnt match'           
        else :
            error_msg = 'Invalid password'  

    return render(request,'patient/pt_change-password.html',{'error_msg' : error_msg, 'success_msg' : success_msg})

def patient_profile(request):
    patient_profile = Patient.objects.get(id = request.session['patient'])
    return render(request,'patient/patient_profile.html', {'patient': patient_profile})

def register(request):
    return render(request,'patient/register.html')

def patient_edit(request):

    if request.method == 'POST':
        patient_edit = Patient.objects.get(id = request.session['patient'])
        patient_edit.patient_name = request.POST['p_name']
        patient_edit.address = request.POST['p_address']
        patient_edit.age = request.POST['p_age']
        patient_edit.gender = request.POST['p_gender']
        patient_edit.blood_grp = request.POST['blood_grp']
        patient_edit.phone = request.POST['phone']
        patient_edit.save()
        return redirect('patient:my-pro')
        
    patient_edit = Patient.objects.get(id = request.session['patient'])
    
    return render(request,'patient/pt_edit_profile.html', {'patient': patient_edit})

def appt_1(request):
    departments = Department.objects.all()
    availability = Consultation.objects.all()
    
    return render(request,'patient/appt_1.html', {'departments' : departments, })

def appt_2(request):

    doctor_id = request.GET['dr']
    doctor_record = Doctor.objects.get(id = doctor_id)

    consultation_record = Consultation.objects.filter(doctor = doctor_id).order_by('day').values()
    
    if request.method == 'POST' :
        pass
    
    return render(request,'patient/appt_2.html', {'doctor' :doctor_record,'consultation' : consultation_record })

def appt_3(request):
    


    if request.method == 'POST' :
        
        patient_name = request.POST['p_name']
        gender  = request.POST['gender']
        mobile = request.POST['mobile']
        age = request.POST['age']
        selected_date = datetime.strptime(request.GET.get('date'), '%Y-%m-%d').date().strftime('%d-%m-%Y')
        dr = request.GET.get('dr')
        selected_time = request.GET.get('time')
        reference_no = 'Ref-' + str(randint(1111,9999)) +'-Hms-' + mobile[6:10]

        if request.POST['apt']=="staffBook":
            sid=request.session['staff']
            new_booking  = Booking(
                            # patient_id = request.session['patient'],
                            patient_name = patient_name,gender = gender,
                            mobile = mobile, age = age,
                            doctor_id = dr,booking_date = selected_date,
                            time = selected_time, reference_no = reference_no
                            )

            new_booking.save()

            return redirect('patient:appointment_4' ,new_booking.id )
        if request.POST['apt']=="Book":
            pid=request.session['patient']
            new_booking  = Booking(
                            patient_id = pid,
                            patient_name = patient_name,gender = gender,
                            mobile = mobile, age = age,
                            doctor_id = dr,booking_date = selected_date,
                            time = selected_time, reference_no = reference_no
                            )

            new_booking.save()
            return redirect('patient:appointment_4', new_booking.id )

        


    dr_id = request.GET['dr']
    selected_time = request.GET['time']
    selected_date = datetime.strptime(request.GET['date'], '%Y-%m-%d').date().strftime('%d-%m-%Y')
    doctor = Doctor.objects.get(id = dr_id)
    doctor_name = doctor.doctor_name
    fee = doctor.fee
    department = doctor.department.department


    
    context = {
        'dr_name' : doctor_name,
        'dep' : department,  
        'selected_date' : selected_date,
        'selected_time' :selected_time,
        'fee': fee
    }

    return render(request,'patient/appt_3.html',context)

def appt_4(request,bid):
    # latest_booking = Booking.objects.filter(patient = id).last()
    latest_booking = Booking.objects.get(id=bid)
    doctor_name = latest_booking.doctor.doctor_name
    dep = latest_booking.doctor.department.department
    reference_no = latest_booking.reference_no
    booking_date = latest_booking.booking_date
    booking_time = latest_booking.time

    context = {
        'doctor_name' : doctor_name,
        'dep' : dep,
        'reference_no' : reference_no,
        'booking_date' : booking_date,
        'booking_time' : booking_time

    }
    return render(request,'patient/appt_4.html',  context)




    

def my_bookings(request):
    booking_records = Booking.objects.filter(patient = request.session['patient'], status= 'booked')
    return render(request,'patient/my_bookings.html', {'booking_records' : booking_records})


def get_doctors(request):
    dept_id = request.POST['id']
    doctors = Doctor.objects.filter(department = dept_id)
    data = [ {'dr_id' : dr.id,'dr_name' : dr.doctor_name} for dr in doctors]
    return JsonResponse({'doctors':data,})


def check_availability(request):

    dr_id = request.POST['dr_id']
    selected_day = request.POST['selected_day']
    
    selected_date = datetime.strptime(request.POST['selected_date'], '%Y-%m-%d').date().strftime('%d-%m-%Y')
    

    
    
    print('doctor is ', dr_id, 'day is ',selected_date)
    consultation_record = Consultation.objects.filter(doctor = dr_id, day = selected_day)
    
    if consultation_record :
        available = True

        
        slots =generate_slot(dr_id,selected_date,selected_day)
        print('frm views',slots)
        return JsonResponse({'availability': available,'consultation_record' : '','bookings' :slots })
        
        
    else:
        available = False

        
        return JsonResponse({'availability': available,})


def logout(request):
    if 'patient' in request.session:
        del request.session['patient']
        request.session.flush()
        return redirect('common:com-home')


def cancel_booking(request,id):
     
    record = Booking.objects.get(id = id)
    record.status = 'cancelled'
    record.save()
    return redirect('patient:booking_history')

def booking_history(request):
    booking_records = Booking.objects.filter(Q(status = 'cancelled') | Q(status = 'consulted'),patient = request.session['patient'])
    # bid=booking_records
    # prescriptions = Presciption.objects.get(id=bid)
    
    
    return render(request, 'patient/booking_history.html',{'booking_records' :booking_records,'prescriptions':prescriptions})

def view_Prescription(request):
    bid=request.POST['bid']
    print(bid)
    # bid=booking_records
    booking=Booking.objects.get(id=bid)
    booking_set={'id':booking.id,'reference_no':booking.reference_no,'patient_name': booking.patient_name, 'booking_date':booking.booking_date, 'doctor_id':booking.doctor_id}
    doctor_name=booking.doctor.doctor_name
    prescriptions = Presciption.objects.filter(booking_id=bid)   
    serialized_set = [{ 'id' : p.id, 'medicine_name' : p.medicine_name,'days':p.days,'medicine_time':p.medicine_time,'intake_time':p.intake_time,'booking_id':p.booking_id }  for p in prescriptions]
    # serialized_data = PrescriptionSerializer(data = prescriptions,many = True)
    return JsonResponse({'data':serialized_set,'booking':booking_set,'doctor_name':doctor_name})

patient/templates/patient/appointment.html
{% extends 'patient/patient_home.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}

<section class="page-title bg-1">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="block text-center">
					<span class="text-white">Book your Seat</span>
					<h1 class="text-capitalize mb-5 text-lg">Appoinment</h1>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="appoinment section">
	<div class="container">
		<div class="row">
			<div class="col-lg-4">
				<div class="mt-3">
					<div class="feature-icon mb-3">
						<i class="icofont-support text-lg"></i>
					</div>
					<span class="h3">Call for an Emergency Service!</span>
					<h2 class="text-color mt-3">+84 789 1256 </h2>
				</div>
			</div>

			<div class="col-lg-8">
				<div class="appoinment-wrap mt-5 mt-lg-0 pl-lg-5">
					<h2 class="mb-2 title-color">Book an appoinment</h2>
					<p class="mb-4"> make your booking.</p>
					<form id="#" class="appoinment-form" method="POST" action="#">
						<div class="row">
							<div class="col-lg-6">
								<div class="form-group">
									<select class="form-control" id="exampleFormControlSelect1">
										<option>select department</option>
										<option>Heart Centre</option>
										<option>Neuro Science</option>
										<option>Liver and gastro science</option>
										<option>Women Care</option>
										<option>Child Care</option>
										<option> orthopaedics</option>
										<option> Renal Care</option>
										<option> pulmonology</option>
										<option> Endocrine sciences</option>
										<option> opthalmology</option>
										<option>Dental Care</option>
										<option> Surgical oncology</option>
										<option> psycyhiatry </option>
										<option> Anaesthesiology</option>
										<option> Dermatology</option>
										<option> Radiology</option>
									</select>

								</div>
							</div>
							<div class="col-lg-6">
								<div class="form-group">
									<select class="form-control" id="exampleFormControlSelect2">
										<option>Select Doctors</option>
										<option>Software Design</option>
										<option>Development cycle</option>
										<option>Software Development</option>
										<option>Maintenance</option>
										<option>Process Query</option>
										<option>Cost and Duration</option>
										<option>Modal Delivery</option>
									</select>
								</div>
							</div>

							<div class="col-lg-6">
								<div class="form-group">
									<input name="date" id="date" type="text" class="form-control"
										placeholder="dd/mm/yyyy">
								</div>
							</div>

							<div class="col-lg-6">
								<div class="form-group">
									<input name="mob" id="mob" type="text" class="form-control"
										placeholder="Mobile Number">
								</div>
							</div>
							<div class="col-lg-6">
								<div class="form-group">
									<input name="name" id="name" type="text" class="form-control"
										placeholder="First Name">
								</div>
							</div>

							<div class="col-lg-6">
								<div class="form-group">
									<input name="name" id="name" type="text" class="form-control"
										placeholder="Last Name">
								</div>
							</div>
						</div>
						<div class="form-group-2 mb-4">
							<textarea name="message" id="message" class="form-control" rows="6"
								placeholder="Your Message"></textarea>
						</div>

						<a class="btn btn-main btn-round-full" href="{% url 'patient:confirm' %}">Make Appoinment<i
								class="icofont-simple-right ml-2"></i></a>
					</form>
				</div>
			</div>
		</div>
	</div>
	</div>
</section>

{% endblock %}

patient/templates/patient/appt_2.html
{% extends 'patient/appt_1.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

<link rel="stylesheet" href="//fonts.googleappis.com/css?family=Roboto:300,400,500,700|Material+Icons">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

<link rel="stylesheet" href="{% static 'css/appt_2.css' %}">
<script src="{% static 'js/appointment.js' %}"></script>

<style>
    #div_slot {
        display: none;
    }

    #btn_proceed {
        display: none;
    }

    #time_slot {
        display: flex;
    }

    .session-btn {
        width: 160px;
        padding: 10px;
        margin: 10px;
        height: 60px;
        font-size: 14px;
        border-radius: 10px;

    }


    #err_div {
        display: none;
        color: red;
        text-align: center;
        margin-top: 20px;
        font-size: 30px;
    }
</style>

{% endblock %}


{% block content %}

<!-- row start  -->
<div class="row d-flex h-100 dr_details">

    <div class="col-1 arw">
        <a href="{% url 'patient:appointment_1' %}"> <span class="material-symbols-outlined btn" id="arrow_left">
                keyboard_arrow_left
            </span></a>
    </div>

    <div class="col-5">
        <div class="card" style="border-radius: 15px;">
            <div class="card-body p-4">
                <div class="d-flex text-black">
                    <div class="flex-shrink-0">
                        <img src="https://care.bestdocapp.com/_nuxt/img/male_doctor.7fec7ec.svg"
                            alt="Generic placeholder image" class="img-fluid"
                            style="width: 80px; height: 80px; border-radius: 10px;" />
                    </div>
                    <div class="flex-grow-1 ms-3">
                        <h5 class="mt-4 mb-1">Dr. {{ doctor.doctor_name | title }} ({{ doctor.qualification | upper }} )
                        </h5>
                        <span><input type="hidden" name="dr_id" id="dr_id" value="{{ doctor.id }}"></span>
                        <p class="mb-2 pb-1" style="color: #2b2a2a;">

                            {{ doctor.department.department | upper }}
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-4"></div>

    <div class="col-2">
        <div class="card fees">
            <div class="card-body p-4">
                <div class="v-card" style="width: 150px;">
                    <span class="body-1">Fee*</span> <br>
                    <span class="title"> <b>₹{{ doctor.fee }}</b> </span>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- row end  -->

<!-- row start  -->

<div class="row">
    <div class="col-md-12">

        <p>Available Days : </p>
        <p>


        <table>
            <tr>
                <th>Day</th>
                <th>Time</th>
            </tr>
            {% for record in consultation %}

            <tr>

                <td>{{ record.day |title }}</td>
                <td>{{ record.time }}</td>
            </tr>

            {% endfor %}
        </table>

        </p>

    </div>
</div>

<div class="row">
    <div class="col-4"></div>
    <div class="col-7">


        <table style="width: 500px;border-collapse: separate; border-spacing: 10px;">
            <tr>
                <td> <label for="date">Consultation Date</label></td>
            </tr>
            <tr>
                <td>
                    <input placeholder="Select date" type="date" id="consultation_date" name="consultation_date"
                        class="form-control">
                </td>
                <td>

                    <a type="button" id='btn_proceed' class="btn btn-primary"> PROCEED</a>
                </td>
            </tr>
        </table>
        <div class="md-form md-outline input-with-post-icon datepicker">



        </div>

    </div>
    <div class="col-4"></div>
</div>
<!-- row end  -->

<!-- row start  -->

<div id="div_slot">

    <div class="row slot">
        <div class="col-12">
            <p> Available Slots/Tokens </p>
        </div>
    </div>
    <!-- row end  -->

    <hr class="bg-dark border-2 border-top border-dark w-70" style="margin-left: 10px;">

    <!-- row start  -->
    <div class="row slot">

        <div class="col-12" id="time_slot">

            <!-- display button here -->


        </div>

        <div class="col-1"></div>
    </div>



    <div class="row slot">
        <div class="col-5"></div>
        <div class="col-2">

            <!-- button  -->
        </div>
        <div class="col-5"></div>
    </div>
</div>
<div id="err_div">Doctor Not Available For Selected Date</div>


<script src="https://cdn.jsdelivr.net/npm/moment@2.29.4/moment.min.js"></script>
<script>
    var show_proceed = false;
    var btn_id = 0;
    var session_div = document.getElementById('time_slot')
    var query_string = window.location.search
    var urlParamsArr = new URLSearchParams(query_string)
    var dr_id = urlParamsArr.get('dr')
    console.log(dr_id)
    var days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];




    $('#consultation_date').change(function () {

        let dt1 = $('#consultation_date').val()



        var dt = new Date($('#consultation_date').val())
        var cd = new Date()
        
        var cd1=cd.setDate(cd.getDate() - 1)

        var selected_day = days[dt.getDay()]
        $('#time_slot').empty()
        console.log(selected_day)
        console.log($(this).val())
        $.ajaxSetup({
            headers: {
                "X-CSRFToken": '{{csrf_token}}'
            }
        })

        if(dt < cd1){
            console.log("dt < cd1")
            console.log(dt,cd1)
            alert("invalid date")
            
        }
        else{
            $.ajax({

                url: "{% url 'patient:check-availability' %}",
                type: 'POST',
                data: {
                    dr_id: dr_id,
                    'selected_day': selected_day,
                    'selected_date': $('#consultation_date').val()
                },
    
                success: function (response) {
    
                    let status = response.availability
                    var records = response.consultation_record
    
    
                    if (status == true) {
    
                        $('#div_slot').show()
                        $('#err_div').hide()
    
                        console.log('bookings', response.bookings)
    
    
                        let records = response.consultation_record
    
                        console.log(response.consultation_record)
    
    
    
                        var bookings = response.bookings[0]
    
                        btn_no = 1
    
                        var today1 = new Date().getHours().toString()
                        
    
                       
                        for (let time in bookings) {
                            time1 = moment(time, ["h:mm A"]).format("HH").toString();
                            
                            console.log(time , bookings[time] ,today1,time1);
                            
                            let btn = document.createElement("button")
                            let btn_id = 'btn' + btn_no
                            btn.setAttribute('id', btn_id)
                            btn.setAttribute('onclick', 'display()')
                            btn.setAttribute('class', 'session-btn btn-border btn-time')
    
                            if ( time1 <= today1 ) {
    
                                btn.setAttribute('disabled', 'true')
                            }
                            if(bookings[time] == 'booked'){
                                btn.setAttribute('disabled', 'true')
                            }
                            btn.innerHTML = time
                            session_div.append(btn)
                            btn_no++
                        }
    
    
    
                    }
    
                    else {
    
                        $('#div_slot').hide()
                        $('#err_div').show()
                        console.log('no')
    
                    }
                }
    
    
            })

        }


       
    })


    var selected_slot;
    var selected_btn;
    function display() {


        console.log(event.target.id, '////')
        selected_slot = document.getElementById(event.target.id)
        let all_btn = document.getElementsByClassName('btn-time')
        selected_btn = event.target.id
        for (let i = 0; i < all_btn.length; i++) {

            all_btn[i].style.backgroundColor = ''
        }


        // alert(selected_slot.innerHTML)

        selected_slot.style.backgroundColor = "green"
        $('#btn_proceed').show()
    }

    $('#btn_proceed').click(function () {



        let selected_time = document.getElementById(selected_btn).innerHTML
        console.log(selected_time)
        let selected_date = $('#consultation_date').val()


        window.location.href = "{% url 'patient:appointment_3' %}?dr=" + dr_id + "&date=" + selected_date + "&time=" + selected_time

    })

</script>


<script>


</script>

{% endblock %}

patient/templates/patient/confirmation.html
{% extends 'patient/patient_home.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}

<section class="section confirmation">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-8">
				<div class="confirmation-content text-center">
					<i class="icofont-check-circled text-lg text-color-2"></i>
					<h2 class="mt-3 mb-4">Your Password has changed </h2>
				</div>
			</div>
		</div>
	</div>
</section>

{% endblock %}

patient/templates/patient/my_bookings.html
{% extends 'patient/patient_base.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}


<h1 style="color: rgb(6, 6, 165); text-align: center;">
    Appointment List
  </h1>
  
  <section class="appoinment section">
      <div class="container">
        <div class="row">
          {% if booking_records %}
            <table class="table table-primary table-striped">
                <tr>
                    <th>Sl No</th>
                    <th> Reference No</th>
                    <th>Patient Name</th>
                    <th> Doctor </th>
                    <th> Date </th>
                    <th> Time </th>
                    <th> Status </th>
                    {% if record.status == 'booked' %}
                    <th> Action </th>
                   {% endif %}
                </tr>
                {% for record in booking_records %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ record.reference_no }}</td>				
                    <td> {{ record.patient.patient_name | title }} </td>
                    <td> {{ record.doctor.doctor_name | title }} </td>
                    <td> {{ record.booking_date }} </td>
                    <td> {{ record.time }} </td>
                    
                    <td> {{ record.status }}</td>
                    {% if record.status == 'booked' %}
                    <td> <a href="{% url 'patient:cancel_booking' record.id %}" class="btn btn-danger"> Cancel </a>  </td>


                    {%  endif %}


                  </tr>

                {% endfor %}


               
              </table> 

              {% else %}

              <h2> No Records Found</h2>
              
              {% endif %}
        </div>
      </div>

    </section>

    

{% endblock %}

patient/templates/patient/pt_change-password.html
{% extends 'patient/patient_home.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href=" {% static 'css/pt_chg-pwd.css' %}">
<link rel="stylesheet" href=" {% static 'js/pt_chg-pwd.js' %}">
{% endblock %}

{% block content %}
<br><br><br>
<section class="section mb-5 mt-5">
    <div class="container ">
        <div class="row justify-content-center">
            <div class="col-lg-11 text-center">
                <div id="container">
                    <div id="header"></div>
                    <div id="form">
                        <form method="POST">
                            {% csrf_token %}
                            <input type="password" placeholder="Old Password" name="old_pswd" id="passOld"> <br><br>

                            <input type="password" placeholder="New Password" name="new_pswd" id="passOne"> <br><br>

                            <input type="password" placeholder="Confirm Password" name="confirm_pswd" id="passTwo">
                            <br><br><br>
                            <div class="pass-sub">
                                <a href="{% url 'patient:confirm' %}">

                                    <input type="button" value="Submit" id="btn1" class="btn-primary">
                                </a>
                            </div>
                        </form>
                        <p class="text-success"></p>{{ success_msg }}</p>
                        <p class="text-danger"></p>{{ error_msg }}</p>
                    </div>
                    <div id="footer" class="incorrect"></div>
                </div>
            </div>
        </div>
    </div> <br><br><br>
</section>


{% endblock %}