common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('', views.home, name='com-home'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('departments', views.dept, name='depts'),
    path('services', views.service, name='services'),
    path('department/<int:id>', views.department_details, name='department_details'),
    path('doctor/<int:id>', views.doctor_details, name='doctor_details'),
    path('doctor', views.doctor, name='dr'),
    path('user-type', views.user_type, name='user_type'),
    path('login', views.login, name='login'),
    path('register', views.patient_registration, name='pat_register'),
    path('make-appointment',views.make_appointment,name = 'make_appointment')
]

hospital_mgt/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('patient/', include('patient.urls')),
    path('doctor/', include('doctor.urls')),
    path('hms_admin/', include('hms_admin.urls')),
    path('staff/', include('staff.urls'))
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from . import views

app_name = 'patient'

urlpatterns = [
    path('home', views.home, name='home'),
    path('appointment', views.appointment, name='appointment'),
    path('confirmation', views.confirmation, name='confirm'),
    path('my-bookings', views.my_bookings, name='bookings'),
    path('my-prescriptions', views.prescriptions, name='prescriptions'),
    path('change-password', views.change_password, name='chg-pwd'),
    path('my-profile', views.patient_profile, name='my-pro'),
    path('register', views.register, name='pt_reg'),
    path('edit_patient_profile', views.patient_edit, name='edit'),
    path('appointment-1', views.appt_1, name='appointment_1'),
    path('appointment-2', views.appt_2, name='appointment_2'),
    path('appointment-3', views.appt_3, name='appointment_3'),
    path('booking-confirmation/<int:bid>', views.appt_4, name='appointment_4'),
    # path('offline_booking',views.offline_booking,name = 'offline_booking'),
    path('my-bookings', views.my_bookings, name='my_bookings'),
    path('get-doctors', views.get_doctors, name='get_doctors'),
    path('check-availability', views.check_availability, name='check-availability'),
    path('booking/cancel/<int:id>',views.cancel_booking,name = 'cancel_booking'),
    path('logout',views.logout,name = 'logout'),
    path('booking/history',views.booking_history,name='booking_history'),
    path('view_Prescription',views.view_Prescription,name='view_Prescription')
]

staff/urls.py
from django.urls import path
from . import views

app_name = 'staff'

urlpatterns = [
    path('home', views.staff_home, name='staff_home'),
    path('register',views.registration,name = 'register'),
    path('appointment/', views.appointments, name='appointment'),
    path('patient_search/', views.patient_search, name='patient-search'), 
    path('staff/', views.staff_list, name = 'staff-list'),
    path('profile/', views.profile, name="staff-prof"),
    path('logout/',views.log_out,name = 'logout')
]

staff/models.py
from django.db import models

# Create your models here.

staff/views.py
from django.shortcuts import render,redirect

from common.models import Patient
from patient.models import Booking

# Create your views here.
def staff_home(request):
    return render(request,'staff/staff_home.html')



def appointments(request):
    booking = Booking.objects.all()
    return render(request,'staff/appointments.html',{'booking':booking})

def registration(request):

    error_msg = ''
    success_msg = ''
    if request.method == 'POST':

        name = request.POST['p_name']
        address = request.POST['p_address']
        age = request.POST['p_age']
        blood_group = request.POST['p_blood']
        contact = request.POST['p_contact']
        dob = request.POST['p_dob']
        gender = request.POST['gender']
        email = request.POST['p_mail']

        record_exist = Patient.objects.filter(email = email).exists()

        if not record_exist :
            if 'pic' in request.FILES : # here pic is the name attribute of fileuploader
                pic = request.FILES['pic']
        
                patient_record = Patient( patient_name = name ,email = email, address = address , age = age , blood_grp = blood_group , 
                phone = contact , dob = dob , gender = gender , pic = pic )
                
            else :

                patient_record = Patient( patient_name = name ,email = email, address = address , age = age , blood_grp = blood_group , 
                phone = contact , dob = dob , gender = gender )

            
            patient_record.save()
            success_msg = 'Record Added Succesfully'

        else:
            error_msg = 'Email Exists'

    return render(request,'staff/registration.html',{'success_msg':success_msg,'error_msg':error_msg})

def patient_search(request):
    patient = Patient.objects.all()
    return render(request,'staff/patient_search.html',{'patient':patient})
   
def staff_list(request):
    patient_list = Booking.objects.all()
    return render(request,'staff/staff.html',{'patient_list':patient_list})

def profile(request):
    return render(request,'staff/staff_profile.html')

def log_out(request):
    del request.session['staff']
    request.session.flush()
    return redirect('common:com-home')


    

staff/templates/staff/appointments.html
{% extends 'staff/staff_masterpage.html' %}
{% load static %}

{% block header %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">


{% endblock %}

{% block content %}


<h1 style="color: rgb(6, 6, 165); text-align: center;">
  Appointment List
</h1>

<section class="appoinment section">
    <div class="container">
      <div class="row">
          <table class="table table-primary table-striped">
              <tr>
                  <th>Sl No</th>
                  <th>Patient</th>
                  <th> Doctor </th>
                  <th> Department </th>
                  <th> Date </th>
                  <th> Time </th>
                  <th> Status </th>
                  <th> Action </th>
              </tr>
              {% for booking in booking %}
              <tr>
                  <td>{{forloop.counter}}</td>				
                  <td> {{booking.patient_name}}</td>
                  <td> {{booking.doctor.doctor_name}}</td>
                  <td> {{booking.doctor.department.department}}</td>
                  <td> {{booking.booking_date}} </td>
                  <td> {{booking.time}} </td>
                  <td> {{booking.status}}</td>
                  <td> <button type="button" class="btn btn-light"> Cancel </button>  </td>
              </tr>
             {% endfor %}
            </table>    
      </div>
    </div>
  </section>

{% endblock %}

staff/templates/staff/patient_search.html
{% extends 'staff/staff_masterpage.html' %} 
{% load static %} 

{% block header %}

<link rel="stylesheet" href="{% static 'css/patient_search.css' %}" />

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />

{% endblock %} 

{% block content %}

<div class="container-fluid">
	
	<h1 style="color: rgb(6, 6, 165); text-align: center;" class="mb-2">
		Patients List
	  </h1>

	<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name" />
{% for patient in patient %}
	<ul id="myUL">
		<li><a href="{% url 'patient:my-pro' %}">{{patient.patient_name}}</a></li>
		<!-- <li><a href="#">Agnes</a></li>

		<li><a href="#">Billy</a></li>
		<li><a href="#">Bob</a></li>

		<li><a href="#">Calvin</a></li>
		<li><a href="#">Christina</a></li>
		<li><a href="#">Cindy</a></li> -->
	</ul>
	{% endfor %}
</div>



	<script>
		function myFunction() {
			var input, filter, ul, li, a, i, txtValue;
			input = document.getElementById("myInput");
			filter = input.value.toUpperCase();
			ul = document.getElementById("myUL");
			li = ul.getElementsByTagName("li");
			for (i = 0; i < li.length; i++) {
				a = li[i].getElementsByTagName("a")[0];
				txtValue = a.textContent || a.innerText;
				if (txtValue.toUpperCase().indexOf(filter) > -1) {
					li[i].style.display = "";
				} else {
					li[i].style.display = "none";
				}
			}
		}
	</script>


{% endblock %}

staff/templates/staff/registration.html
{% extends 'staff/staff_masterpage.html' %}
{% load static %}

{% block header %}

<link rel="stylesheet" href=" {% static 'css/regn-form.css' %}">

{% endblock %}


{% block content %}

<section class="h-100" style=" background: #223a66;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
                <div class="card card-registration my-4">
                    <div class="row g-0">
                        <div class="col-xl-6 d-none d-xl-block">
                            <br><br>
                            <img src="https://marvel-b1-cdn.bc0a.com/f00000000027094/ix-cdn.b2e5.com/images/27094/27094_3ecebd037d0e48248ae08246bddc547e_1556211385.jpeg"
                                alt="Sample photo" class="img-fluid regn">

                        </div>
                        <div class="col-xl-6">
                            <div class="card-body p-md-5 text-black">
                                <h3 class="mb-5 text-uppercase">Patient registration form</h3>
                                {{success_msg}}
                                {{error_msg}}
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" for="form3Example1m">Name</label>
                                            <input type="text" name="p_name" id="form3Example1m"
                                                class="form-control form-control-lg" />

                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" for="form3Example1n">Age</label>
                                            <input type="text" name="p_age" id="form3Example1n"
                                                class="form-control form-control-lg" />

                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 mb-4">
                                        <div class="form-outline">

                                            <label class="form-label" for="form3Example1m1">Date of Birth</label>
                                            <input type="date" name="p_dob" id="form3Example1m1"
                                                class="form-control form-control-lg" />
                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-4">
                                        <div class="form-outline">
                                            <label class="form-label" for="form3Example1n1"> Blood Group </label>
                                            <input type="text" name="p_blood" id="form3Example1n1"
                                                class="form-control form-control-lg" />
                                          
                                        </div>
                                    </div>
                                </div>

                                <div class="d-md-flex justify-content-start align-items-center mb-4 py-2">

                                    <h6 class="mb-0 me-4">Gender &nbsp; : &nbsp;&nbsp; </h6>

                                    <div class="form-check form-check-inline mb-0 me-4">
                                        <input class="form-check-input" type="radio" name="gender"
                                            id="femaleGender" value="female" />
                                        <label class="form-check-label" for="femaleGender">Female</label>
                                    </div>

                                    <div class="form-check form-check-inline mb-0 me-4">
                                        <input class="form-check-input" type="radio" name="gender"
                                            id="maleGender" value="male" />
                                        <label class="form-check-label" for="maleGender">Male</label>
                                    </div>

                                    <div class="form-check form-check-inline mb-0">
                                        <input class="form-check-input" type="radio" name="gender"
                                            id="otherGender" value="others" />
                                        <label class="form-check-label" for="otherGender">Other</label>
                                    </div>
                                </div>

                                <div class="form-outline mb-4">
                                    <label class="form-label" for="form3Example9">Contact No</label>
                                    <input type="text" name="p_contact" id="form3Example9" class="form-control form-control-lg" />
                                  
                                </div>

                                <div class="form-outline mb-4">
                                    <label class="form-label" for="form3Example9">Email</label>
                                    <input type="text" name="p_mail" id="form3Example9" class="form-control form-control-lg" />
                                  
                                </div>

                                <div class="form-outline mb-4">
                                    <label class="form-label" for="form3Example8">Address</label> <br>
                                    <textarea class="form-control form-control-lg" name="p_address" id="" cols="52" rows="5"></textarea>
                                </div>
                   

                                <div class="d-flex justify-content-end pt-3">
                                    <button type="button" class="btn btn-light btn-lg">Reset all</button>
                                    <button type="submit" class="btn btn-primary btn-lg ms-2">Submit form</button>
                                </div>


                            </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

staff/templates/staff/staff.html
{% extends 'staff/staff_masterpage.html' %}
{% load static %}

{% block header %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">


{% endblock %}

{% block content %}

<h1 style="color: rgb(6, 6, 165); text-align: center;">
  Generate Prescription
</h1>

<section class="section">

    <div class="container"> 

      <div class="row">
          <table class="table table-primary table-striped">
              <tr>
                  <th>Sl No</th>
                  <th>Patient name</th>
                  <th>Doctor name</th>
                  <th>Department</th>
                  <th>Contact number</th>
                  <!-- <th> Status </th> -->
                  <th>Prescription</th>
              </tr>
              {% for i in patient_list %}
              <tr>
                  <td>{{forloop.counter}}</td>		
                  <td>{{i.patient_name}}</td>		
                  <td>{{i.doctor.doctor_name}}</td>
                  <td>{{i.doctor.department.department}}</td>
                  <td>{{i.mobile}}</td>
                  <!-- <td> Active</td> -->
                  <td> <button type="button" class="btn btn-light"> Print </button>  </td>
              </tr>
             {% endfor %}
            </table>    
      </div>
    </div>
  </section>

{% endblock %}

staff/templates/staff/staff_masterpage.html
{% load static %}
<!-- All other pages extends this page -->

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="description" content="Orbitor,business,company,agency,modern,bootstrap4,tech,software" />
    <meta name="author" content="themefisher.com" />

    <title>Novena- Health & Care Medical template</title>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="/images/favicon.ico" />

    <!-- bootstrap.min css -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" />
    <!-- Icon Font Css -->
    <link rel="stylesheet" href="{% static 'plugins/icofont/icofont.min.css' %}" />
    <!-- Slick Slider  CSS -->
    <link rel="stylesheet" href=" {% static 'plugins/slick-carousel/slick/slick.css' %}" />
    <link rel="stylesheet" href=" {% static 'plugins/slick-carousel/slick/slick-theme.css' %}" />

    <!-- Main Stylesheet -->
    <link rel="stylesheet" href=" {% static 'css/style.css' %}" />

    <link rel="stylesheet" href=" {% static 'css/modal.css' %}" />

    <link rel="stylesheet" href=" {% static 'css/cards.css' %}" />
    <!-- <link rel="stylesheet" href="{% static 'css/home.css' %}" /> -->

    <!-- Logout  -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@48,400,0,0" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block header %}
    <!-- Add style tag for individual pages  -->
    {% endblock %}
</head>

<body id="top">
    <header>
        <div class="header-top-bar">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6">
                        <ul class="top-bar-info list-inline-item pl-0 mb-0">
                            <li class="list-inline-item">
                                <a href="mailto:support@gmail.com"><i
                                        class="icofont-support-faq mr-2"></i>support@novena.com</a>
                            </li>
                            <li class="list-inline-item">
                                <i class="icofont-location-pin mr-2"></i>Address
                                Ta-134/A, New
                                York, USA
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <div class="text-lg-right top-right-bar mt-2
                                mt-lg-0">
                            <a href="tel:+23-345-67890">
                                <span>Call Now : </span>
                                <span class="h4">823-4565-13456</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <nav class="navbar navbar-expand-lg navigation" id="navbar">
            <div class="container">
                <a class="navbar-brand" href="">
                    <!-- <img src="{% static 'images/logo.png' %}" alt="" class="img-fluid" /> -->
                </a>

                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarmain"
                    aria-controls="navbarmain" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="icofont-navigation-menu"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarmain">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'staff:staff_home' %}">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link" href="{% url 'staff:patient-search' %}" id="dropdown02"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Patients</a>
                            <ul class="dropdown-menu" aria-labelledby="dropdown02">
                                <!-- <li>
                                    <a class="dropdown-item" href="{% url 'staff:patient-search' %}">Search Patient</a>
                                </li> -->
                                <li>
                                    <a class="dropdown-item" href="{% url 'staff:register' %}">Registration</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'staff:staff-list' %}">Prescription</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'common:depts' %}">Departments</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'patient:appointment_1' %}">Booking</a>
                        </li>


                         <!-- Avatar -->
                         <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#"
                                id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown"
                                aria-expanded="false">
                                <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img (31).webp"
                                    class="rounded-circle" height="50" alt="Avatar" />
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                               
                                <li>
                                    <a class="dropdown-item" href="{% url 'common:com-home' %}">Logout</a>
                                </li>
                            </ul>
                        </li>


                        <!-- Logout  -->
                        <!-- <li class="nav-item active">
                            <a class="nav-link" href="{% url 'common:com-home' %}">
                                <span class="material-symbols-rounded">
                                    logout </span>
                            </a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    {% block content %}

    {% endblock %}

    <!-- footer Start -->
    <footer class="footer section gray-bg">
        <div class="container">
            <div class="row">

                <!-- <div class="col-lg-4 mr-auto col-sm-6">
					<div class="widget mb-5 mb-lg-0">
						<div class="logo mb-4">
							<img src="{% static 'images/logo.png' %}" alt="" class="img-fluid">
						</div>
						<p>Tempora dolorem voluptatum nam vero assumenda voluptate, facilis ad eos obcaecati tenetur
							veritatis eveniet distinctio possimus.</p>

						<ul class="list-inline footer-socials mt-4">
							<li class="list-inline-item"><a href="https://www.facebook.com/themefisher"><i
										class="icofont-facebook"></i></a></li>
							<li class="list-inline-item"><a href="https://twitter.com/themefisher"><i
										class="icofont-twitter"></i></a></li>
							<li class="list-inline-item"><a href="https://www.pinterest.com/themefisher/"><i
										class="icofont-linkedin"></i></a></li>
						</ul>
					</div>
				</div> -->

                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="widget mb-5 mb-lg-0">
                        <h4 class="text-capitalize mb-3">Department</h4>
                        <div class="divider mb-4"></div>

                        <ul class="list-unstyled footer-menu lh-35">
                            <li><a href="#">Surgery </a></li>
                            <li><a href="#">Women's Health</a></li>
                            <li><a href="#">Radiology</a></li>
                            <li><a href="#">Cardiac</a></li>
                            <li><a href="#">Medicine</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="widget mb-5 mb-lg-0">
                        <h4 class="text-capitalize mb-3">Support</h4>
                        <div class="divider mb-4"></div>

                        <ul class="list-unstyled footer-menu lh-35">
                            <li><a href="#">Terms & Conditions</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Company Support </a></li>
                            <li><a href="#">FAQuestions</a></li>
                            <li><a href="#">Company Licence</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="widget widget-contact mb-5 mb-lg-0">
                        <h4 class="text-capitalize mb-3">Get in Touch</h4>
                        <div class="divider mb-4"></div>

                        <div class="footer-contact-block mb-4">
                            <div class="icon d-flex align-items-center">
                                <i class="icofont-email mr-3"></i>
                                <span class="h6 mb-0">Support Available for 24/7</span>
                            </div>
                            <h4 class="mt-2"><a href="tel:+23-345-67890">Support@email.com</a></h4>
                        </div>

                        <div class="footer-contact-block">
                            <div class="icon d-flex align-items-center">
                                <i class="icofont-support mr-3"></i>
                                <span class="h6 mb-0">Mon to Fri : 08:30 - 18:00</span>
                            </div>
                            <h4 class="mt-2"><a href="tel:+23-345-67890">+23-456-6588</a></h4>
                        </div>
                        <ul class="list-inline footer-socials mt-4">
                            <li class="list-inline-item"><a href="https://www.facebook.com/themefisher"><i
                                        class="icofont-facebook"></i></a></li>
                            <li class="list-inline-item"><a href="https://twitter.com/themefisher"><i
                                        class="icofont-twitter"></i></a></li>
                            <li class="list-inline-item"><a href="https://www.pinterest.com/themefisher/"><i
                                        class="icofont-linkedin"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="footer-btm py-4 mt-5">
                <div class="row align-items-center justify-content-between">
                    <div class="col-lg-6">
                        <div class="copyright">
                            &copy; Copyright Reserved to <span class="text-color">Novena</span> by <a
                                href="https://themefisher.com/" target="_blank">Themefisher</a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="subscribe-form text-lg-right mt-5 mt-lg-0">
                            <form action="#" class="subscribe">
                                <input type="text" class="form-control" placeholder="Your Email address">
                                <a href="#" class="btn btn-main-2 btn-round-full">Subscribe</a>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <a class="backtop js-scroll-trigger" href="#top">
                            <i class="icofont-long-arrow-up"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- 
    Essential Scripts
    =====================================-->
    <!-- Main jQuery -->
    <script src="{% static 'plugins/jquery/jquery.js' %}
            plugins/jquery/jquery.js"></script>
    <!-- Bootstrap 4.3.2 -->
    <script src="{% static 'plugins/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/counterup/jquery.easing.js' %}"></script>
    <!-- Slick Slider -->
    <script src="{% static 'plugins/slick-carousel/slick/slick.min.js' %}"></script>
    <!-- Counterup -->
    <script src=" {% static 'plugins/counterup/jquery.waypoints.min.js' %}"></script>
    <script src=" {% static 'plugins/shuffle/shuffle.min.js' %}"></script>
    <script src=" {% static 'plugins/counterup/jquery.counterup.min.js' %}"></script>
    <!-- Google Map -->
    <script src=" {% static 'plugins/google-map/map.js' %}"></script>
    <script
        src="
            https://maps.googleapis.com/maps/api/js?key=AIzaSyAkeLMlsiwzp6b3Gnaxd86lvakimwGA6UA&callback=initMap"></script>
    <script src=" {% static 'js/script.js' %}"></script>
    <script src=" {% static 'js/contact.js' %}"></script>

</body>

</html>